name: math_game
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  lottie: ^3.1.2

dev_dependencies: 
  #flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/animation/
    
  uses-material-design: true


